### PR TITLE
Remove HTML framework so that the resulting page can be included into publications.html.

### PR DESCRIPTION
**Pull request by bangerth**
For the moment, let's not merge this yet but discuss whether this is the direction we want to go.

### CODE REVIEW

**Comment by tjhei** [comment]
Yeah, I would prefer we keep things as is because otherwise we can not use/test the html output until we figure out how to merge it and put it online.

**Comment by jppelteret** [comment]
Can we have two templates, with one used for testing and the other for the final render for inclusion into the website?

**Comment by tjhei** [comment]
> Can we have two templates, with one used for testing and the other for the final render for inclusion into the website?

of course!

**Comment by tjhei** [comment]
here is a demo for what I think we can do for the website: we already have a server-side includes, so by moving the static stuff into publications.include and copying the output we have to the webserver, we currently get this: https://dealii.org/temp.html

Before I work on fixing the layout, etc., do we agree that:
- this is all one page (how to cite deal.II and list of publications)? The page is rather long.
- I moved the graph from the sidebar to list further down. This means it is less visible, but it also works on mobile now. I did this mainly to make things easier, though. :-)
- other comments?

**Comment by bangerth** [comment]
The formatting doesn't work right now, but that can wait. I'm ok with leaving the citation info and the publications as is for the moment -- we can split that in a second stage. But I'd like to move the graph to the top again -- I'm ok if you want to put it into the main column, but it should be visible if you get to the page.

**Comment by tjhei** [comment]
> But I'd like to move the graph to the top again

so leave "how to cite deal.II" on the page but move the graph above it? Will do.

**Comment by jppelteret** [comment]
I'm unexpectedly excited about seeing the new publication page go up 🤓

**Comment by bangerth** [comment]
On 3/12/19 2:23 PM, Jean-Paul Pelteret wrote:
> I'm unexpectedly excited about seeing the new publication page go up 🤓

I'm entirely unsurprisingly excited!

**Comment by bangerth** [comment]
No longer relevant following recent patches.

**Pull request closed without merging**
