### PR TITLE
Modified entry lorencioabriljoseantonio2022

### PR DESCRIPTION
**Pull request by Lorenc1o**
- Added an url in which the thesis can be consulted
- Added month
- Changed Bachelor's Thesis from 'type' to 'note' as seen in the repository advice (It appears in the web as Master's Thesis, but it is a Bachelor's Thesis)

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Thanks!

**Comment by marcfehling** [comment]
> * Added an url in which the thesis can be consulted

Thanks for the update! I can't see the URL in the document. Did you miss it by accident?

**Comment by Lorenc1o** [comment]
Sorry, I have done another PR because I had already deleted the previous forked repo. It should be OK now!

**Pull request merged**
