### PR TITLE
Added more entries

### PR DESCRIPTION
**Pull request by juleoc02**
Some of the citations have the same label. I'm unsure how big of an issue this is, as that was also the case in some previously finished citations as well

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Thanks, @juleoc02 ! How much of the list is left at this point?

**Comment by juleoc02** [comment]
I’ve got one thing of lecture notes I’m not quite sure what to do with, and a few articles we haven’t verified as using deal.ii

Sent from my iPhone

On Sep 28, 2020, at 9:43 PM, Wolfgang Bangerth <notifications@github.com> wrote:

﻿

Thanks, @juleoc02<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjuleoc02&data=02%7C01%7CJustin.OConnor%40colostate.edu%7C0acbd9d7456442f1638108d86429e2c8%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637369478345887981&sdata=g%2Bgne500pWRMqfWyIX9MTcThIwkw4KN1xwDqqEOIyTQ%3D&reserved=0> ! How much of the list is left at this point?

**Comment by bangerth** [comment]
On 9/28/20 10:05 PM, juleoc02 wrote:
> I’ve got one thing of lecture notes I’m not quite sure what to do with, and a 
> few articles we haven’t verified as using deal.ii

OK -- please bring it up on Wed during our usual meeting.

**Pull request merged**
