### PR TITLE
Make sure the 9.6 release paper is listed at the top.

### PR DESCRIPTION
**Pull request by bangerth**
We never updated the publications list for the 9.6 release paper.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by blaisb** [comment]
I noticed this was merged without updating the DOI. We still don't have a DOI for the current release right?

**Comment by bangerth** [comment]
Yes, I commented out the DOI. I don't have an up to date DOI, and last someone asked, @tjhei said there isn't one yet.

**Comment by tjhei** [comment]
https://doi.org/10.1515/jnma-2024-0137 but it's not online yet.

**Pull request merged**
