### PR TITLE
Update the entries of #120.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by bangerth** [comment]
I've gone through the entries in #120 and made sure that everything uses deal.II. I had to remove one entry. I added a DOI to another.

**Comment by tjhei** [comment]
```
WARN - Entry 180410120 does not parse correctly

ERROR - BibTeX subsystem: /tmp/3Lc69D2MoW/publications-2018.bib_312.utf8, line 1205, syntax error: found "Journal", expected end of entry ("}" or ")") (skipping to next "@")
```

**Comment by bangerth** [comment]
Works now.

**Pull request merged**
