### PR TITLE
Added new publication for 2022

### PR DESCRIPTION
**Pull request by GiuseppeOrlando878776**
Added "An efficient and accurate implicit DG solver for the incompressible Navier‐Stokes equations" publication published online in "International Journal for Numerical Methods in Fluids". The corresponding code has been submitted for a pull request in the "code-gallery"

### CODE REVIEW

**Comment by peterrum** [comment]
```
publications-2022.bib:79:         title   = {An efficient and accurate implicit {DG} solver for the incompressible {N}avier‐{S}tokes equations},

ERROR: found non-ASCII characters!

script returned exit code 1
```

**Comment by peterrum** [comment]
@GiuseppeOrlando878776 Thanks! I'll try to take a look at your code-gallery contribution in the next days/weeks. We are a bit busy with the next release of the library :(

**Review by peterrum — APPROVED** [review]

**Comment by GiuseppeOrlando878776** [comment]
@peterrum Thanks! I understand very well, take your time, there is no hurry for this. Thanks again

**Pull request merged**
