### PR TITLE
Resolved issue #90

### PR DESCRIPTION
**Pull request by genevaporter**
Eight publications were added to the 2018 and 2019 BIB files.

### CODE REVIEW

**Comment by tjhei** [comment]
fixes #90

**Comment by bangerth** [comment]
Looks good to me.

**Comment by tjhei** [comment]
The tester complains:
```
! Misplaced alignment tab character &.
<argument> Multiscale Modeling &
                                 Simulation
l.60 \addnewbibyear{2018}
```
I think you need to escape the ``&`` in the bibtex. You can test it yourself by compiling the .tex document in the ``offline/`` folder.

**Comment by genevaporter** [comment]
Ok, I'll fix that now!

**Comment by genevaporter** [comment]
Ok, i saw some mistakes that I made yesterday. I didn't commit the 2019 changes correctly (just added 3 entries), and didn't test the bib files myself...maybe there was a more efficient way to test before the pull request than copying and pasting into a tex editor? Also I created 2 pull requests today when I meant to wait until after all my changes and create only 1 pull request.

**Comment by bangerth** [comment]
Nice job, @genevaporter !

**Pull request merged**
