### PR TITLE
Add Rigsby's MS thesis.

### PR DESCRIPTION
**Pull request by bangerth**
The defense is going on as about to happen as I write this :-)

/rebuild

### CODE REVIEW

**Comment by drwells** [comment]
Is there a URL available?

**Comment by bangerth** [comment]
I don't have one, but that's also because the thesis was only defended today and hasn't actually been submitted yet. I just didn't want to forget about it :-)

**Comment by drwells** [comment]
That's a good idea.

I'd prefer to wait until we have a URL so that we don't have to dig through the university library website to find the thesis later.

**Comment by bangerth** [comment]
OK, let's leave this in limbo then until I have a URL -- sometime later this year I hope.

**Comment by bangerth** [comment]
Thanks for checking, @marcfehling ! I added the URL and rebased to master.

**Pull request merged**
