### PR TITLE
Added 2023 and 2024 Publications

### PR DESCRIPTION
**Pull request by narasimhan-2604**
The following publications were added to the repository
(1) 2023:sanjana:swaminathan:parag:chemo
(2) 2023:umair:phani:narasimhan:mapping
(3) 2024:sanjana:narasimhan:parag:stress

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
The tester complains:
```
publications-2023.bib:2048:  doi = {[https://doi.org/10.1016/j.mechmat.2023.104738}](https://doi.org/10.1016/j.mechmat.2023.104738%7D),
publications-2023.bib:2063:  doi = {[https://doi.org/10.1016/j.commatsci.2023.112227}](https://doi.org/10.1016/j.commatsci.2023.112227%7D),
ERROR: URL in a field that should only contain a DOI!
```
Can you drop the URL part from the DOIs?

**Comment by narasimhan-2604** [comment]
Sure. Shall I redo it?

**Comment by bangerth** [comment]
Either that, or you can make the changes on the branch, then squash them all into one commit and force push that.

**Comment by marcfehling** [comment]
Superseded by #592.

**Pull request closed without merging**
