### PR TITLE
twick update pubs 2021

### PR DESCRIPTION
**Pull request by tommeswick**
Update pubs year 2021.

### CODE REVIEW

**Comment by masterleinad** [comment]
```
publications-2021.bib:30:abstract = {We describe the Software package LocModFE, which is an implementation of a locally modified finite element method for an accurate solution of interface problems. The code was originally developed in the finite element library Gascoigne 3d and has now been rewritten in the widerspread library deal.II. This makes the concept of locally modified finite elements accessible to many users all over the world. Applications range from simple Poisson interface problems over multi-phase flows to complex multi-physics problems, such as fluid–structure interactions. Being based on deal.II, it provides plenty of possibilities for future extensions, e.g., parallel computing, multigrid solvers or mesh adaptivity.}

publications-2021.bib:84:author={Katrin Mang and Andreas Fehse and Nils Hendrik Kröger and Thomas Wick},

publications-2021.bib:100:author = {Fehse, Andreas and Kröger, Nils Hendrik and Mang, Katrin and Wick, Thomas},
```

**Comment by masterleinad** [comment]
Looks like there are some non-ASCII characters.

**Comment by tommeswick** [comment]
Corrected non-ASCII characters.

**Review by marcfehling — APPROVED** [review]

**Review by jppelteret — APPROVED** [review]
Thank you!

**Pull request merged**
