### PR TITLE
Added Publications

### PR DESCRIPTION
**Pull request by ManaswineeB**
Six new BibTeX entries were added

Umlauts fixed (rebuilt pull request)

There was an umlaut that was showing as an invalid character. Fixed that.

Another Umlaut

Parsing error fixed

### CODE REVIEW

**Comment by drwells** [comment]
Part of #118 (@ManaswineeB did the first part).

**Comment by drwells** [comment]
Thanks a lot for doing this!

**Comment by bangerth** [comment]
I've gone through these entries again and made sure that everything we list is actually using deal.II. The updates are in #127.

**Pull request merged**
