### PR TITLE
jenkins: check for non-ascii chars

### PR DESCRIPTION
**Pull request by tjhei**
see discussion in #32

### CODE REVIEW

**Comment by tjhei** [comment]
okay, with some bash fiddling this now seems to work as intended!

**Comment by jppelteret** [comment]
Awesome, thanks a lot!

**Comment by tjhei** [comment]
This is how it looks when it is broken: https://jenkins.tjhei.info/blue/organizations/jenkins/publication-list/detail/PR-37/10/pipeline

**Comment by jppelteret** [comment]
Its great that it prints out the problematic line :-)

**Comment by tjhei** [comment]
> Its great that it prints out the problematic line :-)

yeah, took me 20 minutes of fiddling to get that to work. :-)

**Pull request merged**
