### PR TITLE
Fixed Salvador2022.

### PR DESCRIPTION
**Pull request by marcfehling**
image

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
If I as a speaker of Italian would have had to spell it, I would have used "Dedè" (it's a bit like how non-German speakers would spell the German name Müller, Mueller, Muller, M"uller etc), but for names you never know if the correct grammar is not always the correct spelling of a name. As the author's own home page http://www1.mate.polimi.it/~dede/ , lists the name you choose, that would be clear.

**Comment by marcfehling** [comment]
> As the author's own home page http://www1.mate.polimi.it/~dede/ , lists the name you choose, that would be clear.

The author also used that particular name in the article itself, which is why I chose that particular name.

`doi2bib` added the `\textquotesingle` command, which caused the trouble. This command needs the `textcomp` package, which we probably do not load.

So we could either add the `textcomp` package somewhere, or opt for changing for the `'` ASCII character as proposed in this PR.

**Comment by marcfehling** [comment]
On the other hand, the author is spelled "Dedè" in [this article](https://www.sciencedirect.com/science/article/pii/S0021999122001450?via%3Dihub). We will need to be consistent with his spelling when adding the paper from #344.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Maybe not optimal, but better than nothing. And @drwells discovered the same one recently.

**Pull request merged**
