### PR TITLE
Add an output template for @inproceedings.

### PR DESCRIPTION
**Pull request by bangerth**
Previously, we default template was used, but that looks wonky for some entries.

### CODE REVIEW

**Comment by bangerth** [comment]
Ping?

**Comment by masterleinad** [comment]
Did you steal this from somewhere?

**Comment by bangerth** [comment]
No, I'm an honest man. I don't steal!

(The real answer is that we have templates for other types of bibtex entries already in this directory, and I just adapted an existing one to the `@inproceedings` case by looking up which kinds of lines can appear in these entries.)

**Pull request merged**
