### PR TITLE
Clean up a few publications from 2018

### PR DESCRIPTION
**Pull request by kronbichler**
this cleans up a few publications where we had only listed preprints, and adds three more publications from 2018/2019 that were missing and are not in #186.

### CODE REVIEW

**Comment by peterrum** [comment]
I have done (more or less) the same in my last commit...

**Comment by kronbichler** [comment]
> I have done (more or less) the same in my last commit...

One of us will need to rebase, given that we have non-redundant data. Let me merge your PR, so I can do the rebase.

**Comment by bangerth** [comment]
Please merge yourself after rebasing.

**Pull request merged**
