### PR TITLE
Narasimhan 2604 my publication

### PR DESCRIPTION
**Pull request by narasimhan-2604**
I have now 
(1) Changed the months to have three characters only
(2) The urls have been removed from the dois
Thank you

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]
The entries are okay now. The issue with the html check is unrelated to your patch. Thank you for the contribution!

**Comment by marcfehling** [comment]
@tjhei The `Out of system resources` for the html test pops up more frequently, but it needs to pass so PRs can be merged. Can we remove the required tag from the html check in the meantime?

**Comment by tjhei** [comment]
I will try to figure out what is going on.

**Comment by marcfehling** [comment]
I have no idea why the CI keeps failing on this PR while other pass. Let me try something out.

**Comment by masterleinad** [comment]
> I have no idea why the CI keeps failing on this PR while other pass. Let me try something out.

It says:
```
There is insufficient memory for the Java Runtime Environment to continue.
Cannot create GC thread. Out of system resources.
```

**Comment by marcfehling** [comment]
I rebased the commits into one and ran the sorting script. I saw that one of the publications was already in our list, so this patch now contains two extra publications.

**Comment by marcfehling** [comment]
CI passes now. Thanks for looking into it @tjhei

**Pull request merged**
