### PR TITLE
Add html generation

### PR DESCRIPTION
**Pull request by tjhei**
- simple version stolen from ASPECT
- uses the jabref inside a docker container
- builds ``publications.html``

We probably need to edit/replace the layout, but this at least "works".

### CODE REVIEW

**Comment by tjhei** [comment]
umlauts are broken, see "Comparison of implicit and explicit". Let me play with this locally some more.

**Comment by jppelteret** [comment]
I'm busy running these through latex (offline), and they're broken there. I guess I should fix those up first. I'll open a PR now for a latex project that builds all of the entries into a PDF.

**Comment by tjhei** [comment]
okay, want to merge this as is for now and see if our other changes fixes the umlauts?

**Comment by jppelteret** [comment]
Sure, sounds good!

**Pull request merged**
