### PR TITLE
Additional 9 entries (Issue #118 part2)

### PR DESCRIPTION
**Pull request by ManaswineeB**

### CODE REVIEW

**Comment by bangerth** [comment]
Did you check that all of these publications actually *use* deal.II, as opposed to just citing a deal.II paper? I think that, for example, the last one you added doesn't actually use deal.II.

**Comment by ManaswineeB** [comment]
> Did you check that all of these publications actually _use_ deal.II, as opposed to just citing a deal.II paper? I think that, for example, the last one you added doesn't actually use deal.II.

I didn't realize that some papers are just citing the work. I'll check in and re-do this list and the last list!

**Comment by bangerth** [comment]
Thanks, @ManaswineeB -- let us know once you want us to think about this again!

**Comment by bangerth** [comment]
Let's merge this, and I'll go through it in a follow-up.

**Comment by bangerth** [comment]
Updates are in #128.

**Pull request merged**
