### PR TITLE
Add hyper.deal release paper

### PR DESCRIPTION
**Pull request by peterrum**
FYI @kkormann @kronbichler

### CODE REVIEW

**Comment by bangerth** [comment]
This is the correct entry:
```
@misc{munch2020hyperdeal,
    title={hyper.deal: An efficient, matrix-free finite-element library for high-dimensional partial differential equations},
    author={Peter Munch and Katharina Kormann and Martin Kronbichler},
    year={2020},
    eprint={2002.08110},
    archivePrefix={arXiv},
    primaryClass={cs.MS}
}
```
You get it via "Export citation" on the arxiv page.

**Comment by kronbichler** [comment]
I guess you still want to change the eprint identifier to `2020.08110` @peterrum :wink:

**Comment by peterrum** [comment]
@bangerth @kronbichler I think it is correct: https://arxiv.org/abs/2002.08110

**Comment by kronbichler** [comment]
You are right, too many 20 and 02 for me today. :rofl:

**Comment by bangerth** [comment]
Yes, correct. But I would still appreciate if you could use the version I copied above since then our scripts automatically generate the correct links.

**Comment by peterrum** [comment]
@bangerth Alright. Done.

**Pull request merged**
