### PR TITLE
Found one of David's publications.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by drwells** [comment]
I'm impressed that they got my UNC address; we submitted this about a year before I moved!

**Comment by drwells** [comment]
The address should be

Gewerbestrasse 11, 6330 Cham, Switzerland

but otherwise this looks good.

**Comment by bangerth** [comment]
Hm, that seems silly. One generally only lists the city -- like "Springer, London, Paris, Tokyo, Heidelberg".

Or should I just remove the line?

**Comment by drwells** [comment]
You're right. I looked at my bib files and I don't list more than the city when I bother with the address; lets keep it like this.

**Pull request merged**
