### PR TITLE
move plot to top of page in html

### PR DESCRIPTION
**Pull request by tjhei**
this is for the dealii.org website. As discussed in #26. See http://dealii.org/temp.html for a demo (in about an hour)

### CODE REVIEW

**Comment by drwells** [comment]
the temp page looks good to me so I approve :+1:. Lets see what others think.

**Comment by bangerth** [comment]
The layout of the page isn't correct, but I'm not sure whether that's because of the mockup or because the markup in the page is incorrect. We can fix this once we're live.

**Comment by tjhei** [comment]
> The layout of the page isn't correct,

Yeah, sorry. I spent some time looking at the various nested divs, but I couldn't figure it out.

**Comment by tjhei** [comment]
Okay, https://www.dealii.org/publications.html is now online. :-)

**Comment by jppelteret** [comment]
Awesome. Thanks a lot Timo!

**Comment by bangerth** [comment]
@tjhei -- I'm playing with the styles. You left the `publications-old.html` file around. Does it still have any use?

**Comment by tjhei** [comment]
> I'm playing with the styles

only edit publications.include, otherwise the changes need to go into the .begin. and .end.layout files in this repo. Does that make sense?


> You left the `publications-old.html` file around. Does it still have any use?

I left it there for reference so we can compare layout and move everything over, etc.. Can go once we are happy.

**Comment by bangerth** [comment]
On 3/13/19 12:21 PM, Timo Heister wrote:
>     I'm playing with the styles
> 
> only edit publications.include, otherwise the changes need to go into the 
> .begin. and .end.layout files in this repo. Does that make sense?

Ah, crap. So how is publications.html then created, and when? How can I test this?


>     You left the |publications-old.html| file around. Does it still have any use?
> 
> I left it there for reference so we can compare layout and move everything 
> over, etc.. Can go once we are happy.

Just zap this stuff. One can always get it out of the repo, but we don't want 
to end up with unused files littering our repositories...

**Comment by bangerth** [comment]
@tjhei -- ping?

**Comment by tjhei** [comment]
> Ah, crap. So how is publications.html then created, and when? How can I test this?

you can make a PR and jenkins will generate the .html and you can download it. Alternatively, you can run ``make`` when you check out the repo (you need docker).

**Comment by bangerth** [comment]
You mean make a PR on the publication-list repo? The problem with downloading the html is that it uses server-side includes, so it's difficult to test locally. 

My question was more how is the `publications.html` on the website updated? It resides in the magic svn repo, but how does do updated versions get in there?

**Pull request merged**
