### PR TITLE
add article

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
Amazing what deal.II is being used for.

**Comment by jppelteret** [comment]
I don't think that we have the two preceding papers that preceded this one listed. Do you want to add them at the same time, or should I just do it in a follow up PR?
https://www.frontiersin.org/articles/10.3389/fphys.2020.00813/full
https://www.frontiersin.org/articles/10.3389/fphys.2020.538522/full

**Review by jppelteret — APPROVED** [review]

**Comment by tjhei** [comment]
done.

**Review by jppelteret — APPROVED** [review]

**Comment by jppelteret** [comment]
Awesome, thanks a lot!

**Pull request merged**
